const ROLE = {
    superAdmin: 'super_admin',
    admin: 'admin',
    user: 'user',
};

const roles = {
    super_admin: [
        'create:user',
        'edit:user',
        'delete:user',
        'list:user',
        'read:user',
        'create:report',
        'delete:report',
        'list:report',
        'read:report',
        'edit:report',
        'delete:video',
        'list:video',
        'approve:video',
        'destroy:conversations',
        'list:conversations',
        'list:categories',
        'edit:categories',
        'delete:categories',
        'create:categories',
        'analytics',
    ],
    admin: [
        'create:user',
        'edit:user',
        'list:user',
        'read:user',
        'create:report',
        'delete:report',
        'list:report',
        'read:report',
        'edit:report',
        'delete:video',
        'list:video',
        'approve:video',
        'destroy:conversations',
        'list:conversations',
        'list:categories',
        'edit:categories',
        'delete:categories',
        'create:categories',
        'analytics',
    ],
    user: [
        'list:user',
        'read:user',
        'edit:user',
        'delete:user',
        'create:report',
        'delete:report',
        'delete:video',
        'list:video',
    ],
};

export { ROLE };
export default roles;
